# Generated by Django 5.2.9 on 2025-12-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnormalBehavior',
            fields=[
                ('abnormal_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('no_show', 'No Show'), ('overtime', 'Overtime')], max_length=20)),
                ('record_time', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(db_column='space_id', on_delete=django.db.models.deletion.CASCADE, to='space.studyspace')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='space.user')),
            ],
            options={
                'db_table': 'abnormal_behavior',
            },
        ),
    ]
