# Generated by Django 5.2.9 on 2025-12-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('in_use', 'In Use'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='reserved', max_length=21),
        ),
    ]
